Allow the add-on store to be launched on Python 3.11 (#15570)
Summary of the issue:
When the add-on store is launched, the following error is generated:

Traceback (most recent call last):
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\__init__.pyc", line 400, in onAddonStoreCommand
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\__init__.pyc", line 216, in popupSettingsDialog
  File "gui\_addonStoreGui\controls\storeDialog.pyc", line 56, in __init__
  File "gui\_addonStoreGui\controls\messageDialogs.pyc", line 236, in __init__
TypeError: StaticText.Wrap(): argument 1 has unexpected type 'float'
Description of how this pull request fixes the issue:
In wxpython 4.2, Wrap expects an int. Round the scale factor.