Fix-up #14070: No more error at edge of table with MSHtml (#14298)
Summary of the issue:
In MSHtml container, e.g. NVDA's browseable message, the table edge is not reported. The following error is found instead:

ERROR - scriptHandler.executeScript (23:32:09.385) - MainThread (6444):
error executing script: <bound method DocumentWithTableNavigation.script_nextColumn of <virtualBuffers.MSHTML.MSHTML object at 0x0953F690>> with gesture 'alt+contrôle+flèche droite'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 289, in executeScript
  File "documentBase.pyc", line 480, in script_nextColumn
  File "documentBase.pyc", line 417, in _tableMovementScriptHelper
  File "documentBase.pyc", line 362, in _tableFindNewCell
  File "virtualBuffers\__init__.pyc", line 674, in _getNearestTableCell
TypeError: cannot unpack non-iterable _TableCell object
Description of user facing changes
No more error reported at edge and the edge is reported.

Description of development approach
The dataclass documentBase._TableCell was added in #14070. More specifically, DocumentWithTableNavigation._getTableCellCoords now returns _TableCell. But some usages of the return of this function have been forgotten.
This PR fixes this.