Use nvda-microsoft-ui-uiautomation
Rather than building the submodule every time NVDA is built, pre-build
this dependency.

The dependency is built on Github, however, the generated headers
require that the same Winsdk / compiler is used when using the headers,
this something we can gaurantee for developers, or appveyor.

The build fails with:
build\x86\microsoft-ui-uiautomation\include\winrt/Microsoft.UI.UIAutomation.h
(7): error C2338: Mismatched C++/WinRT headers.

build\x86\microsoft-ui-uiautomation\include\winrt/Microsoft.UI.UIAutomation.h
(8): warning C4005: 'CPPWINRT_VERSION': macro redefinition

C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt\winrt/base.h
(6): note: see previous definition of 'CPPWINRT_VERSION'

C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\cppwinrt\winrt/base.h
(6): warning C4005: 'CPPWINRT_VERSION': macro redefinition

build\x86\microsoft-ui-uiautomation\include\winrt/Microsoft.UI.UIAutomation.h
(8): note: see previous definition of 'CPPWINRT_VERSION'