Fix error when displaying math panel #19820
Link to issue number:

Fix-up of #19740
Summary of the issue:

After the merge of #19740, the math panel cannot be displayed and the following error is logged:

ERROR - unhandled exception (15:06:18.687) - MainThread (1844):
Traceback (most recent call last):
  File "gui\settingsDialogs.py", line 6230, in onCategoryChange
    super().onCategoryChange(evt)
    ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "gui\settingsDialogs.py", line 750, in onCategoryChange
    self._doCategoryChange(newIndex)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "gui\settingsDialogs.py", line 733, in _doCategoryChange
    newCat = self._getCategoryPanel(newCatId)
  File "gui\settingsDialogs.py", line 660, in _getCategoryPanel
    panel = cls(parent=self.container)
  File "gui\settingsDialogs.py", line 392, in __init__
    self._buildGui()
    ~~~~~~~~~~~~~~^^
  File "gui\settingsDialogs.py", line 402, in _buildGui
    self.makeSettings(self.settingsSizer)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "gui\settingsDialogs.py", line 2771, in makeSettings
    languageIndex = next(filter(lambda idxLang: idxLang[1].code == mathLang, self.languageOptions))[0]
                    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "gui\settingsDialogs.py", line 2771, in <lambda>
    languageIndex = next(filter(lambda idxLang: idxLang[1].code == mathLang, self.languageOptions))[0]
                                                ~~~~~~~^^^
TypeError: 'LanguageInfo' object is not subscriptable
I

Description of user facing changes:

The math panel can be displayed again.
Description of developer facing changes:

None
Description of development approach:

    Used enumerate on the language list to be able to retrieve its index.
    Also used a generator expression instead of the use of the filter function + lambda since the previous code seemed less readable and less modern Python syntax. This is debatable though, and I can restore the old syntax, just adding enumerate, if you prefer.
    Added a DEBUGWARNING log when the config language is not found in supported languages.