Fix checkPot for plural (#19158)
Fixes issue found while working on #19059
Summary of the issue:

In #19059, commit 9595711, an error is raised during check Pot:

scons: *** [tests\checkPot] IndexError : list index out of range
Traceback (most recent call last):
  File "D:\a\nvda\nvda\.venv\Lib\site-packages\SCons\Action.py", line 1434, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
  File "D:\a\nvda\nvda\tests\sconscript", line 21, in checkPotAction
    return checkPot.checkPot(source[0].abspath)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "D:\a\nvda\nvda\tests\checkPot.py", line 142, in checkPot
    msgid += getStringFromLine(line)
             ~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\a\nvda\nvda\tests\checkPot.py", line 201, in getStringFromLine
    quoted = line.split(" ", 1)[1]
             ~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
Error: Process completed with exit code 1.

The test should pass or fail but no error should be raised.

The error occurs if a msgid command containing a multi-line string is followed by a msgid_plural command. This had probably never happened before the string introduced in #19059.
Description of user facing changes:

The Python script to check Pot does not raise an error before completing.
Description of developer facing changes:

N/A
Description of development approach:

Take into account the presence of msgid_plural token. Taken into account that a multi-line string in the msgid command can end:

    either with a msgstr command
    or a msgid_plural command