Provide speech symbols file name path on creation (#17346)
Fixes #17344

Summary of the issue:
The SpeechSymbols only sets the filename to write to when the dictionary is loaded.
Before 826ef91, dictionary files were always loaded before they were saved.
Afterwards, dictionaries are saved without being loaded.
When trying to save dictionary files the following error occurs, due to no file name being set

Speaking [LangChangeCommand ('en_US'), 'pressed']
ERROR - unhandled exception (17:00:20.842) - MainThread (9964):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 5350, in onOk
  File "characterProcessing.pyc", line 364, in save
ValueError: No file name
Description of user facing changes
Users can now save the speech dictionary dialog.
Add-ons which use custom speech dictionaries are also saved correctly now.

Description of development approach
Create optional parameter to set filename path for speech dictionaries.