Gracefully ignore NVDANotInitializedError when scheduling WASAPI idle check. (#15145)
Fixes #15143.

Summary of the issue:
When playing the start sound, NVDA can fail with this error:

  File "nvwave.pyc", line 975, in _scheduleIdleCheck
  File "core.pyc", line 928, in callLater
core.NVDANotInitializedError: Cannot schedule callable, wx.App is not initialized
Description of user facing changes
Fixed the error.

Description of development approach
Feeding WASAPI audio schedules an idle check, which uses core.callLater. That will fail if the wx.App isn't initialised yet.

We now just catch this and ignore it. playWaveFile closes the stream after playing anyway, so this first idle check isn't important.