Do not present usage information anymore when NVDA cannot restart (#14398)
Linked to #14251

Summary of the issue:
In #14251, the following error message is seen when restarting:

usage: nvda.exe [-h] [-q] [-k] [-f LOGFILENAME]
[-l {10,12,15,20,30,40,50,100}] [-c CONFIGPATH]
[--lang LANGUAGE] [-m] [-s] [--disable-addons]
[--debug-logging] [--no-logging] [--no-sr-flag]
[--install | --install-silent | --create-portable | --create-portable-silent]
[--portable-path PORTABLEPATH] [--launcher]
[--enable-start-on-logon True|False] [--copy-portable-config]
[--ease-of-access]

error: Couldn't terminate existing NVDA process, abandoning start:
Exception: [WinError 5] Access is denied.

This message is quite confusing and only the end of the message is relevant; all the usage part is not relevant when restarting NVDA with normal options (e.g. no option at all)

Description of user facing changes
In case NVDA cannot restart, the error message will not show the command line usage anymore.

Description of development approach
Use winUser.MessageBox instead of parser.error.