Work around wxWidgets assertion (PR #12292)
See issue #12220

There was a wxAssertion error when closing braille or speech settings panels.

ERROR - unhandled exception (09:33:35.263) - MainThread (7112):
wx._core.wxAssertionError: C++ assertion ""GetWindow() != 0"" failed at ..\..\src\common\wincmn.cpp(3919) in wxWindowAccessible::GetDescription(): 

The above exception was the direct cause of the following exception:
SystemError: <class 'wx._core.WindowDestroyEvent'> returned a result with an error set

There is a lot more information about the investigation on the issue.

This PR provides a workaround, the true cause of this assertion has not yet been determined.
However in the meantime this PR will prevent the log error, and any additional instability in 
WX that may occur due to ending up in this situation.