Avoid error in PowerPoint slideshows when focus highlighting is on (#17724)
Summary of the issue:
NVDA raises the following error when the highlighter is on in a PowerPoint slide show

Error running handler <bound method NVDAHighlighter.handleBrowseModeMove of <visionEnhancementProviders.NVDAHighlighter.NVDAHighlighter object at 0x088D25D0>> for <extensionPoints.Action object at 0x0640C350>
Traceback (most recent call last):
  File "extensionPoints\__init__.pyc", line 56, in notify
  File "extensionPoints\util.pyc", line 216, in callWithSupportedKwargs
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 497, in handleBrowseModeMove
  File "visionEnhancementProviders\NVDAHighlighter.pyc", line 481, in updateContextRect
  File "vision\util.pyc", line 79, in getContextRect
  File "vision\util.pyc", line 48, in getCaretRect
  File "vision\util.pyc", line 94, in getRectFromTextInfo
  File "baseObject.pyc", line 39, in __get__
  File "NVDAObjects\__init__.pyc", line 72, in _get_boundingRects
AttributeError: 'ReviewableSlideshowTreeInterceptor' object has no attribute 'hasIrrelevantLocation'

Description of user facing changes
No longer an error in the log

Description of development approach
Added an override of boundingRects on SlideShowTreeInterceptorTextInfo