Fix installer bug where install fails if registry entries exist but NVDA is not installed (#15767)
A user reported the installer failing to start with the following traceback:

INFO - __main__ (17:42:54.836) - MainThread (11512):
Starting NVDA version 2023.3
CRITICAL - __main__ (17:42:55.691) - MainThread (11512):
core failure
Traceback (most recent call last):
  File "config\__init__.pyc", line 179, in isInstalledCopy
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Program Files (x86)\\NVDA'
It is expected that this is caused when the registry contains keys suggesting NVDA is installed, but the install directory does not exist.

Description of user facing changes
Installer should be more resilient

Description of development approach
Catch FileNotFoundError when checking if NVDA is installed.