fix up unnamed percent rule to exclude %% (#18503)
Summary of the issue:

The regex to check for unnamed string interpolations doesn't support the %% symbol, which escapes %.
This leads to certain usages of it raising incorrect interpolation errors.

File source/locale/tr/LC_MESSAGES/nvda.po: 1 error
Message starting on line 10286
Original: "%s%%"
Translated: "%%%s"
Error: unnamed percent interpolations differ
Expected: unnamed percent interpolations in this order: ['%s']
Got: no interpolations

Description of user facing changes:

error fixed for translators
Description of developer facing changes:

none
Description of development approach:

Fixed up regex