Avoid type clash due to typing.List import
Use qualified name.

Otherwise the newly introduced

    from __future__ import annotations

in

    commit feea4aa0aa0a6b12c33ee8dd70f22d76a2cc6d83
    Author: Michael Weghorn <m.weghorn@posteo.de>
    Date:   Wed Nov 27 09:12:38 2024 +0000

        Add type annotation

causes

    source/NVDAObjects/IAccessible/__init__.py:2391:7: F811 Redefinition of unused `List` from line 13
         |
    2391 | class List(IAccessible):
         |       ^^^^ F811
    2392 |     def _get_role(self):
    2393 |         return controlTypes.Role.LIST
         |
         = help: Remove definition: `List`

    Found 1 error.