Typing a dead key no longer throws an error (#18933)
Fixes #18908
Summary of the issue:

After we moved to a tightened ctypes definition for user32.MapVirtualKeyEx, typing dead keys such as an acute on a German keyboard layout would throw an error such as:

  File "keyboardHandler.pyc", line 535, in _get_mainKeyName
ValueError: chr() arg not in range(0x110000)

Description of user facing changes:

No longer throws an error when typing dead keys.
Description of developer facing changes:
Description of development approach:

KeyboardInputGesture.mainKeyName: As MapVirtualKeyEx now correctly returns an unsigned int we must be more explisit about filtering out dead keys. A dead key is denoted when the highest bit is set.