Explisitly link nvdahelperLocal against runtimeobject.lib to allow building on VS build tools 17.14.8 (#18458)
Reported in discussion #18446.
Summary of the issue:

uiaUtils in nvdaHelperLocal uses c++/winrt objects, which require linking against runtimeobject.lib. Previous to the 10.0.2610 Windows SDK version in VS 2022 V17.14.8, this was linked implisitly. It seems now we need to do this explisitly.
This was noticed on some local builds, and on GitHub actions most likely with an image from July 10.
Error:

UIAUtils.obj : error LNK2019: unresolved external symbol _WINRT_IMPL_RoGetActivationFactory@12 referenced in function "struct winrt::hresult __cdecl winrt::impl::get_runtime_activation_factory_impl<0>(struct winrt::param::hstring const &,struct winrt::guid const &,void * *)" (??$get_runtime_activation_factory_impl@$0A@@impl@winrt@@YA?AUhresult@1@ABUhstring@param@1@ABUguid@1@PAPAX@Z)                                 
UIAUtils.obj : error LNK2019: unresolved external symbol _WINRT_IMPL_RoOriginateLanguageException@12 referenced in function "private: void __thiscall winrt::hresult_error::originate(struct winrt::hresult,void *,struct winrt::impl::slim_source_location const &)" (?originate@hresult_error@winrt@@AAEXUhresult@2@PAXABUslim_source_location@impl@2@@Z)                                                                       
build\x86\local\nvdaHelperLocal.dll : fatal error LNK1120: 2 unresolved externals 

Description of user facing changes:

None.
Description of developer facing changes:

NVDA will build again with VS 2022 V17.14.8.
Description of development approach:

Explisitly link nvdaHelperLocal against runtimeobject.lib in nvdaHelper/local/sconscript.