Various fix-up of keep audio awake feature (#16147)
Fix-up of #16099

Fixes #16148

Summary of the issue:
Error when disabling WASAPI and reopening advanced settings:
ERROR - unhandled exception (11:14:54.349) - MainThread (6028):
Traceback (most recent call last):
  File "gui\settingsDialogs.pyc", line 4517, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 693, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 675, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 603, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 362, in __init__
  File "gui\settingsDialogs.pyc", line 372, in _buildGui
  File "gui\settingsDialogs.pyc", line 3514, in makeSettings
  File "gui\settingsDialogs.pyc", line 3259, in __init__
  File "gui\settingsDialogs.pyc", line 3352, in _onWasapiChange
  File "gui\guiHelper.pyc", line 232, in Enable
TypeError: Window.Enable(): argument 1 has unexpected type 'FeatureFlag'
ERROR - unhandled exception (11:14:54.361) - MainThread (6028):
Traceback (most recent call last):
  File "gui\guiHelper.pyc", line 218, in _onEnableChanged
TypeError: Window.Enable(): argument 1 has unexpected type 'FeatureFlag'
Oversight in AdvancedPanelControls.haveConfigDefaultsBeenRestored in settingsDialogs.py.

In settingsDialogs.py, rename variable to be consistent with the GUI ("silence" -> "keep audio awake")

Documentation (User Guide and Change log) updates

Description of user facing changes
The option is enabled or disabled depending on the real current WASAPI state, not the state defined in the configuration for the next restart of NVDA.
The "keep audio awake" option is moved to audio settings
The documentation does not mention "playing silence" at all anymore
Description of development approach
For point 1: use real WASAPI state instead of what is in the config for the next restart, as it was already done in other audio settings depending on WASAPI.