Fix `exc_info` parameter for `log.exception` (#16867)
According to its type hints and its code, log.exception can accept either True or a tuple as returned by sys.exc_info() as exc_info parameter.
However, at least one function in NVDA expect it to also accept an exception instance: see log.exception call in _getCurrentSessionInfoEx in winAPI\sessionTracking.py.
Forcing an exception in the try block of this function unproperly raises:
TypeError: 'RuntimeError' object is not subscriptable

Also according to my tests, logHandler.log._log seems to accept for exc_info parameter: True, an exception instance or an exception tuple (in the format returned by sys.exc_info()), so it would make sense to be consistent with it.

At last, according to Python doc of logging module, logging function can accept an exception instance as exc_info parameter from Python 3.5 onward:

Changed in version 3.5: The exc_info parameter can now accept exception instances.

Description of user facing changes
_getCurrentSessionInfoEx can now also accept an exception instance as exc_info parameter.

Description of development approach
Modified the function's code and signature.