Fixed a bug where NVDA sometimes was unable to reset the configuration to factory defaults when using the NVDA+control+r command (#16919)
fixes #16896

Summary of the issue:
Sometimes, when pressing the NVDA+control+r command three times, NVDA wouldn't reset the configuration to factory defaults, but instead produce the following error
ERROR - keyboardHandler.internal_keyDownEvent (10:14:40.187) - winInputHook (13232):
internal_keyDownEvent
Traceback (most recent call last):
File "keyboardHandler.pyc", line 245, in internal_keyDownEvent
File "inputCore.pyc", line 535, in executeGesture
AttributeError: 'NoneType' object has no attribute 'suppressClearBrailleRegions'

Description of user facing changes
The user will reliably be able to reset the configuration to factory defaults with the NVDA+control+r command

Description of development approach
the suppressCancelSpeech function is only defined and called if braille.handler is not None, otherwise, speech.cancelSpeech is called